import { BenefitProps } from '@/components/benefits/benefit-card';

export const mockAllBenefits: BenefitProps[] = [
  {
    id: '1',
    title: 'Health Insurance',
    details: 'Comprehensive medical, dental, and vision coverage with top-tier network access and full preventative care.',
    description: 'Comprehensive medical, dental, and vision coverage',
    imageUrl: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=500&auto=format&fit=crop&q=80',
    minTimeAtCompany: 'Immediate',
    maxUsageDurationMonths: 12,
    maxUsageCount: 'Unlimited',
    thumbnailInitials: 'HE',
    isEnjoying: false,
  },
  {
    id: '2',
    title: '401(k) Plan',
    details: 'Retirement savings with company match up to 4% of annual gross salary with immediate vesting options.',
    description: 'Retirement savings with company match up to 4%',
    imageUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=500&auto=format&fit=crop&q=80',
    minTimeAtCompany: '3 months',
    maxUsageDurationMonths: 24,
    maxUsageCount: 'Unlimited',
    thumbnailInitials: 'RE',
    isEnjoying: false,
  },
  {
    id: '3',
    title: 'Wellness Program',
    details: 'Full access to premium gym networks, mental wellness apps, and personalized monthly fitness coaching.',
    description: 'Gym membership and mental health support',
    imageUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
    minTimeAtCompany: '1 month',
    maxUsageDurationMonths: 12,
    maxUsageCount: 1,
    thumbnailInitials: 'WE',
    isEnjoying: false,
  },
  {
    id: '4',
    title: 'Life Insurance',
    details: 'Life insurance coverage up to 2x annual salary with flexible beneficiary options and additional voluntary add-ons.',
    description: 'Life insurance coverage at 2x annual salary',
    imageUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=500&auto=format&fit=crop&q=80',
    minTimeAtCompany: '6 months',
    maxUsageDurationMonths: 12,
    maxUsageCount: 1,
    thumbnailInitials: 'LI',
    isEnjoying: false,
  },
  {
    id: '5',
    title: 'Parental Leave',
    details: 'Fully paid leave for new parents following birth, adoption, or foster placement for up to 16 continuous weeks.',
    description: 'Paid leave for new parents following birth or adoption',
    imageUrl: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?w=500&auto=format&fit=crop&q=80',
    minTimeAtCompany: '1 year',
    maxUsageDurationMonths: 4,
    maxUsageCount: 2,
    thumbnailInitials: 'PA',
    isEnjoying: false,
  },
  {
    id: '6',
    title: 'Premium Gym Membership',
    details: 'VIP pass to 500+ partner fitness studios nationwide including pilates, yoga, and personal trainer consultations.',
    description: 'Access to 500+ gyms nationwide, unlimited classes',
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=80',
    minTimeAtCompany: '2 months',
    maxUsageDurationMonths: 6,
    maxUsageCount: 1,
    thumbnailInitials: 'GY',
    isEnjoying: false,
  },
  {
    id: '7',
    title: 'Courier & Shipping Discounts',
    details: 'Save up to 20% on domestic and international express courier parcel shipments for personal use.',
    description: 'Up to 20% discount on courier and shipping services',
    imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=500&auto=format&fit=crop&q=80',
    minTimeAtCompany: 'Immediate',
    maxUsageDurationMonths: 12,
    maxUsageCount: 12,
    thumbnailInitials: 'CO',
    isEnjoying: false,
  },
  {
    id: '8',
    title: 'Transportation Benefits',
    details: 'Monthly pre-tax transit passes, commuter subsidies, and free parking access near regional hub offices.',
    description: 'Monthly transit passes and parking subsidies',
    imageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=500&auto=format&fit=crop&q=80',
    minTimeAtCompany: 'Immediate',
    maxUsageDurationMonths: 12,
    maxUsageCount: 'Unlimited',
    thumbnailInitials: 'TR',
    isEnjoying: false,
  },
];

export const mockEnjoyingBenefits: BenefitProps[] = [
  {
    id: '1',
    title: 'Health Insurance',
    details: 'Comprehensive medical, dental, and vision coverage with top-tier network access and full preventative care.',
    description: 'Comprehensive medical, dental, and vision coverage',
    imageUrl: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=500&auto=format&fit=crop&q=80',
    minTimeAtCompany: 'Immediate',
    maxUsageDurationMonths: 12,
    maxUsageCount: 'Unlimited',
    thumbnailInitials: 'HE',
    isEnjoying: true,
  },
  {
    id: '2',
    title: '401(k) Plan',
    details: 'Retirement savings with company match up to 4% of annual gross salary with immediate vesting options.',
    description: 'Retirement savings with company match up to 4%',
    imageUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=500&auto=format&fit=crop&q=80',
    minTimeAtCompany: '3 months',
    maxUsageDurationMonths: 24,
    maxUsageCount: 'Unlimited',
    thumbnailInitials: 'RE',
    isEnjoying: true,
  },
  {
    id: '3',
    title: 'Wellness Program',
    details: 'Full access to premium gym networks, mental wellness apps, and personalized monthly fitness coaching.',
    description: 'Gym membership and mental health support',
    imageUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=80',
    minTimeAtCompany: '1 month',
    maxUsageDurationMonths: 12,
    maxUsageCount: 1,
    thumbnailInitials: 'WE',
    isEnjoying: true,
  },
];


